spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          consumerProperties:
            group.id: notification-service-group # Özelleştirilmiş bir grup kimliği
            auto-offset-reset: latest # En son offsetten başlamak için

      rabbit:
        binder:
          addresses: rabbitmq:5672
          username: guest
          password: guest

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8888/eureka/
