spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      rabbit:
        binder:
          addresses: rabbitmq:5672
          username: guest
          password: guest
  datasource:
    url: jdbc:postgresql://postgres:5432/ms-customer-service
    username: postgres
    password: test
server:
  port: 8081
