spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service-swagger
            uri: http://customer-service:8081
            predicates:
              - Path=/customer-service/v3/api-docs
            filters:
              - SetPath=/v3/api-docs

          - id: order-service-swagger
            uri: http://order-service:8082
            predicates:
              - Path=/order-service/v3/api-docs
            filters:
              - SetPath=/v3/api-docs

          - id: customer-service
            uri: http://customer-service:8081
            predicates:
              - Path=/customer-service/**
            filters:
              - RewritePath=/customer-service/(?<segment>.*), /$\\{segment}

          - id: order-service
            uri: http://order-service:8082
            predicates:
              - Path=/order-service/**
            filters:
              - RewritePath=/order-service/(?<segment>.*), /$\\{segment}

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8888/eureka/
