spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-customer-service
    username: postgres
    password: test

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
