spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service-swagger
            uri: http://localhost:8081
            predicates:
              - Path=/customer-service/v3/api-docs
            filters:
              - SetPath=/v3/api-docs

          - id: customer-service
            uri: http://localhost:8081
            predicates:
              - Path=/customer-service/**
            filters:
              - RewritePath=/customer-service/(?<segment>.*), /$\\{segment}

          - id: order-service-swagger
            uri: http://localhost:8082
            predicates:
              - Path=/order-service/v3/api-docs
            filters:
              - SetPath=/v3/api-docs

          - id: order-service
            uri: http://localhost:8082
            predicates:
              - Path=/order-service/**
            filters:
              - RewritePath=/order-service/(?<segment>.*), /$\\{segment}

          - id: identity-service-swagger
            uri: http://localhost:8083
            predicates:
              - Path=/identity-service/v3/api-docs
            filters:
              - SetPath=/v3/api-docs

          - id: identity-service
            uri: http://localhost:8083
            predicates:
              - Path=/identity-service/**
            filters:
              - RewritePath=/identity-service/(?<segment>.*), /$\\{segment}

          - id: notification-service-swagger
            uri: http://localhost:8085
            predicates:
              - Path=/notification-service/v3/api-docs
            filters:
              - SetPath=/v3/api-docs

          - id: notification-service
            uri: http://localhost:8085
            predicates:
              - Path=/notification-service/**
            filters:
              - RewritePath=/notification-service/(?<segment>.*), /$\\{segment}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
